FROM pytorch/pytorch:1.5.1-cuda10.1-cudnn7-runtime

RUN pip install --no-cache-dir https://rosh-public.s3-eu-west-1.amazonaws.com/radon-dev/cuda-10.1/torch-1.5/torch_radon-0.0.1-cp37-cp37m-linux_x86_64.whl